name: websocket-server-liveness-tester
region: nyc
services:
- http_port: 8080
  image:
    registry: jdoleary1991
    registry_type: DOCKER_HUB
    repository: websocket-server-liveness-tester
    tag: 1.0.0 
  instance_count: 1
  instance_size_slug: basic-xxs
  name: websocket-server-liveness-tester
  routes:
  - path: /
